-- Módulo de Relatórios de Despesas / Adiantamentos.
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.expense_reports (
  id uuid primary key default gen_random_uuid(),
  report_number bigint generated by default as identity unique,
  status text not null default 'draft'
    check (status in ('draft', 'pending_approval', 'approved', 'provisioned', 'payment_scheduled', 'paid')),
  source_company text default 'IRACAMBI',
  company_code text,
  cost_center text,
  program_id uuid references public.programs(id) on delete set null,
  project_name text,
  project_code text,
  person_id uuid references public.persons(id) on delete set null,
  user_name text,
  user_cpf text,
  user_phone text,
  user_role text,
  registration_number text,
  period_start date,
  period_end date,
  travel_route text,
  purpose text,
  advance_amount numeric(12,2) not null default 0 check (advance_amount >= 0),
  payment_method text check (payment_method in ('checking', 'savings', 'check') or payment_method is null),
  bank_name text,
  bank_branch text,
  bank_branch_digit text,
  bank_account text,
  bank_account_digit text,
  expense_items jsonb not null default '[]'::jsonb check (jsonb_typeof(expense_items) = 'array'),
  submitted_at timestamptz,
  approved_by uuid references public.persons(id) on delete set null,
  approved_at timestamptz,
  provisioned_by uuid references public.persons(id) on delete set null,
  provisioned_at timestamptz,
  payment_due_date date,
  paid_at timestamptz,
  paid_by uuid references public.persons(id) on delete set null,
  payment_receipt jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_end >= period_start)
);

-- Atualização segura para instalações que já executaram uma versão anterior.
alter table public.expense_reports
  add column if not exists approved_by uuid references public.persons(id) on delete set null,
  add column if not exists approved_at timestamptz,
  add column if not exists provisioned_by uuid references public.persons(id) on delete set null,
  add column if not exists provisioned_at timestamptz,
  add column if not exists payment_due_date date,
  add column if not exists paid_at timestamptz,
  add column if not exists paid_by uuid references public.persons(id) on delete set null,
  add column if not exists payment_receipt jsonb;

-- Somente banco e forma de crédito são obrigatórios no formulário.
alter table public.expense_reports
  alter column source_company drop not null,
  alter column project_name drop not null,
  alter column user_name drop not null,
  alter column period_start drop not null,
  alter column period_end drop not null,
  alter column purpose drop not null;

alter table public.expense_reports drop constraint if exists expense_reports_status_check;
update public.expense_reports set status = 'pending_approval' where status = 'submitted';
alter table public.expense_reports add constraint expense_reports_status_check
  check (status in ('draft', 'pending_approval', 'approved', 'provisioned', 'payment_scheduled', 'paid'));

create table if not exists public.expense_report_notifications (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.expense_reports(id) on delete cascade,
  recipient_id uuid not null references public.persons(id) on delete cascade,
  actor_id uuid references public.persons(id) on delete set null,
  type text not null check (type in ('submitted', 'approval_requested', 'approved', 'provisioned', 'payment_scheduled', 'paid')),
  title text not null,
  content text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value)
values ('expense_report_settings', '{"send_email": false}'::jsonb)
on conflict (key) do nothing;

create table if not exists public.mileage_rates (
  id uuid primary key default gen_random_uuid(),
  vehicle_type text not null check (vehicle_type in ('car', 'motorcycle')),
  amount_per_km numeric(10,4) not null check (amount_per_km > 0),
  effective_date date not null,
  created_at timestamptz not null default now(),
  unique (vehicle_type, effective_date)
);

create index if not exists mileage_rates_lookup_idx
  on public.mileage_rates(vehicle_type, effective_date desc);

create index if not exists expense_report_notifications_recipient_idx
  on public.expense_report_notifications(recipient_id, created_at desc);
create unique index if not exists expense_report_notifications_unique_event_idx
  on public.expense_report_notifications(report_id, recipient_id, type);

create index if not exists expense_reports_created_at_idx
  on public.expense_reports(created_at desc);
create index if not exists expense_reports_person_idx
  on public.expense_reports(person_id);
create index if not exists expense_reports_program_idx
  on public.expense_reports(program_id);
create index if not exists expense_reports_status_idx
  on public.expense_reports(status);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists expense_reports_updated_at on public.expense_reports;
create trigger expense_reports_updated_at before update on public.expense_reports
for each row execute function public.set_updated_at();

alter table public.expense_reports enable row level security;
alter table public.expense_report_notifications enable row level security;
alter table public.app_settings enable row level security;
alter table public.mileage_rates enable row level security;

drop policy if exists "expense_reports_select_all" on public.expense_reports;
drop policy if exists "expense_reports_insert_all" on public.expense_reports;
drop policy if exists "expense_reports_update_all" on public.expense_reports;

create policy "expense_reports_select_all" on public.expense_reports
  for select using (true);
create policy "expense_reports_insert_all" on public.expense_reports
  for insert with check (true);
create policy "expense_reports_update_all" on public.expense_reports
  for update using (true) with check (true);

drop policy if exists "expense_notifications_select_all" on public.expense_report_notifications;
drop policy if exists "expense_notifications_insert_all" on public.expense_report_notifications;
drop policy if exists "expense_notifications_update_all" on public.expense_report_notifications;

create policy "expense_notifications_select_all" on public.expense_report_notifications
  for select using (true);
create policy "expense_notifications_insert_all" on public.expense_report_notifications
  for insert with check (true);
create policy "expense_notifications_update_all" on public.expense_report_notifications
  for update using (true) with check (true);

drop policy if exists "app_settings_select_all" on public.app_settings;
drop policy if exists "app_settings_insert_all" on public.app_settings;
drop policy if exists "app_settings_update_all" on public.app_settings;
create policy "app_settings_select_all" on public.app_settings for select using (true);
create policy "app_settings_insert_all" on public.app_settings for insert with check (true);
create policy "app_settings_update_all" on public.app_settings for update using (true) with check (true);

drop policy if exists "mileage_rates_select_all" on public.mileage_rates;
drop policy if exists "mileage_rates_insert_all" on public.mileage_rates;
create policy "mileage_rates_select_all" on public.mileage_rates for select using (true);
create policy "mileage_rates_insert_all" on public.mileage_rates for insert with check (true);
