-- Relatórios mensais de atividades — execute no SQL Editor do Supabase.
create table if not exists public.monthly_activity_reports (
  id uuid primary key default gen_random_uuid(),
  report_number bigint generated by default as identity unique,
  report_type text not null check (report_type in ('individual', 'program')),
  reference_month date not null check (reference_month = date_trunc('month', reference_month)::date),
  program_id uuid references public.programs(id) on delete restrict,
  program_name text not null,
  person_id uuid references public.persons(id) on delete set null,
  responsible_name text not null,
  team_names text[] not null default '{}',
  status text not null default 'draft' check (status in ('draft', 'submitted', 'approved')),
  executive_summary text,
  highlights text,
  challenges text,
  next_month_plan text,
  activity_snapshot jsonb not null default '[]'::jsonb check (jsonb_typeof(activity_snapshot) = 'array'),
  indicators jsonb not null default '[]'::jsonb check (jsonb_typeof(indicators) = 'array'),
  submitted_at timestamptz,
  approved_at timestamptz,
  approved_by uuid references public.persons(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_type, reference_month, program_id, person_id)
);

create unique index if not exists monthly_reports_unique_scope_idx
  on public.monthly_activity_reports (
    report_type,
    reference_month,
    program_id,
    coalesce(person_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

create index if not exists monthly_reports_reference_idx on public.monthly_activity_reports(reference_month desc);
create index if not exists monthly_reports_program_idx on public.monthly_activity_reports(program_id);
create index if not exists monthly_reports_person_idx on public.monthly_activity_reports(person_id);
create index if not exists monthly_reports_status_idx on public.monthly_activity_reports(status);

create or replace function public.set_monthly_report_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists monthly_activity_reports_updated_at on public.monthly_activity_reports;
create trigger monthly_activity_reports_updated_at
before update on public.monthly_activity_reports
for each row execute function public.set_monthly_report_updated_at();

alter table public.monthly_activity_reports enable row level security;

grant select, insert, update, delete on public.monthly_activity_reports to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "monthly_reports_select_all" on public.monthly_activity_reports;
drop policy if exists "monthly_reports_insert_all" on public.monthly_activity_reports;
drop policy if exists "monthly_reports_update_all" on public.monthly_activity_reports;
drop policy if exists "monthly_reports_delete_drafts" on public.monthly_activity_reports;
drop policy if exists "monthly_reports_delete_all" on public.monthly_activity_reports;

create policy "monthly_reports_select_all" on public.monthly_activity_reports for select using (true);
create policy "monthly_reports_insert_all" on public.monthly_activity_reports for insert with check (true);
create policy "monthly_reports_update_all" on public.monthly_activity_reports for update using (true) with check (true);
create policy "monthly_reports_delete_all" on public.monthly_activity_reports for delete using (true);

notify pgrst, 'reload schema';
