-- Gestão de Projetos — cadastro, Kanban, tarefas, riscos, colaboração e notificações.
-- Execute integralmente no SQL Editor do Supabase.

create table if not exists public.management_projects (
  id uuid primary key default gen_random_uuid(),
  project_number bigint generated by default as identity unique,
  title text not null,
  program_id uuid references public.programs(id) on delete set null,
  project_type text not null check (project_type in ('strategic', 'operational', 'emergency', 'mandatory')),
  category text not null,
  status text not null default 'ideas' check (status in ('ideas', 'analysis', 'planning', 'awaiting_approval', 'approved', 'in_progress', 'paused', 'completed', 'cancelled')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'critical')),
  description text not null,
  need_statement text,
  general_objective text,
  specific_objectives jsonb not null default '[]'::jsonb check (jsonb_typeof(specific_objectives) = 'array'),
  expected_results text,
  location text,
  planned_start date,
  planned_end date,
  actual_start date,
  actual_end date,
  manager_id uuid references public.persons(id) on delete set null,
  team_ids uuid[] not null default '{}',
  beneficiaries text,
  partners text,
  funders text,
  planned_budget numeric(14,2) not null default 0 check (planned_budget >= 0),
  actual_budget numeric(14,2) not null default 0 check (actual_budget >= 0),
  committed_budget numeric(14,2) not null default 0 check (committed_budget >= 0),
  funding_source text,
  progress_mode text not null default 'tasks' check (progress_mode in ('manual', 'tasks', 'weighted')),
  manual_progress numeric(5,2) not null default 0 check (manual_progress between 0 and 100),
  cover_url text,
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  notes text,
  created_by uuid references public.persons(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (planned_end is null or planned_start is null or planned_end >= planned_start),
  check (actual_end is null or actual_start is null or actual_end >= actual_start)
);

create table if not exists public.management_project_tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.management_projects(id) on delete cascade,
  stage text,
  title text not null,
  description text,
  responsible_id uuid references public.persons(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'blocked', 'completed', 'cancelled')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'critical')),
  planned_start date,
  planned_end date,
  completed_at timestamptz,
  weight numeric(8,2) not null default 1 check (weight > 0),
  hours numeric(10,2) not null default 0 check (hours >= 0),
  checklist jsonb not null default '[]'::jsonb check (jsonb_typeof(checklist) = 'array'),
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  sort_order integer not null default 0,
  created_by uuid references public.persons(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.management_project_risks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.management_projects(id) on delete cascade,
  title text not null,
  description text,
  probability text not null default 'medium' check (probability in ('low', 'medium', 'high')),
  impact text not null default 'medium' check (impact in ('low', 'medium', 'high', 'critical')),
  response_plan text,
  owner_id uuid references public.persons(id) on delete set null,
  due_date date,
  status text not null default 'open' check (status in ('open', 'mitigating', 'resolved', 'accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.management_project_logs (
  id bigint generated always as identity primary key,
  project_id uuid not null references public.management_projects(id) on delete cascade,
  actor_id uuid references public.persons(id) on delete set null,
  log_type text not null check (log_type in ('created', 'updated', 'status', 'comment', 'task', 'risk', 'file')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.management_project_notifications (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.management_projects(id) on delete cascade,
  recipient_id uuid not null references public.persons(id) on delete cascade,
  actor_id uuid references public.persons(id) on delete set null,
  title text not null,
  content text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.activities add column if not exists management_project_id uuid references public.management_projects(id) on delete set null;

create index if not exists management_projects_status_idx on public.management_projects(status, priority, planned_end);
create index if not exists management_projects_program_idx on public.management_projects(program_id);
create index if not exists management_projects_manager_idx on public.management_projects(manager_id);
create index if not exists management_project_tasks_project_idx on public.management_project_tasks(project_id, status, sort_order);
create index if not exists management_project_risks_project_idx on public.management_project_risks(project_id, status);
create index if not exists management_project_logs_project_idx on public.management_project_logs(project_id, created_at desc);
create index if not exists management_project_notifications_recipient_idx on public.management_project_notifications(recipient_id, read_at, created_at desc);

drop trigger if exists management_projects_updated_at on public.management_projects;
create trigger management_projects_updated_at before update on public.management_projects for each row execute function public.set_updated_at();
drop trigger if exists management_project_tasks_updated_at on public.management_project_tasks;
create trigger management_project_tasks_updated_at before update on public.management_project_tasks for each row execute function public.set_updated_at();
drop trigger if exists management_project_risks_updated_at on public.management_project_risks;
create trigger management_project_risks_updated_at before update on public.management_project_risks for each row execute function public.set_updated_at();

alter table public.management_projects enable row level security;
alter table public.management_project_tasks enable row level security;
alter table public.management_project_risks enable row level security;
alter table public.management_project_logs enable row level security;
alter table public.management_project_notifications enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['management_projects','management_project_tasks','management_project_risks','management_project_logs'] loop
    execute format('drop policy if exists "authenticated_select_%1$s" on public.%1$I', table_name);
    execute format('drop policy if exists "authenticated_insert_%1$s" on public.%1$I', table_name);
    execute format('drop policy if exists "authenticated_update_%1$s" on public.%1$I', table_name);
    execute format('drop policy if exists "authenticated_delete_%1$s" on public.%1$I', table_name);
    execute format('create policy "authenticated_select_%1$s" on public.%1$I for select to authenticated using (true)', table_name);
    execute format('create policy "authenticated_insert_%1$s" on public.%1$I for insert to authenticated with check (true)', table_name);
    execute format('create policy "authenticated_update_%1$s" on public.%1$I for update to authenticated using (true) with check (true)', table_name);
    execute format('create policy "authenticated_delete_%1$s" on public.%1$I for delete to authenticated using (exists (select 1 from public.persons where auth_user_id = auth.uid() and access_role = ''admin''))', table_name);
  end loop;
end $$;

drop policy if exists "project_notifications_select_own" on public.management_project_notifications;
drop policy if exists "project_notifications_insert_authenticated" on public.management_project_notifications;
drop policy if exists "project_notifications_update_own" on public.management_project_notifications;
create policy "project_notifications_select_own" on public.management_project_notifications for select to authenticated
using (recipient_id in (select id from public.persons where auth_user_id = auth.uid()));
create policy "project_notifications_insert_authenticated" on public.management_project_notifications for insert to authenticated with check (true);
create policy "project_notifications_update_own" on public.management_project_notifications for update to authenticated
using (recipient_id in (select id from public.persons where auth_user_id = auth.uid()));

grant select, insert, update, delete on public.management_projects, public.management_project_tasks, public.management_project_risks, public.management_project_logs to authenticated;
grant select, insert, update on public.management_project_notifications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare target_table text;
begin
  if to_regprocedure('public.capture_system_audit()') is not null then
    foreach target_table in array array['management_projects','management_project_tasks','management_project_risks'] loop
      execute format('drop trigger if exists system_audit_trigger on public.%I', target_table);
      execute format('create trigger system_audit_trigger after insert or update or delete on public.%I for each row execute function public.capture_system_audit()', target_table);
    end loop;
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'management_project_notifications') then
    alter publication supabase_realtime add table public.management_project_notifications;
  end if;
end $$;

notify pgrst, 'reload schema';
