-- Autenticação e controle de acesso dos usuários da Agenda Iracambi.
alter table public.persons
  add column if not exists email text,
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists access_role text not null default 'user' check (access_role in ('user', 'admin')),
  add column if not exists must_change_password boolean not null default true,
  add column if not exists failed_login_attempts integer not null default 0,
  add column if not exists locked_at timestamptz,
  add column if not exists last_login_at timestamptz,
  add column if not exists managed_by uuid references public.persons(id) on delete set null;

create unique index if not exists persons_email_unique_idx on public.persons (lower(email)) where email is not null;
create index if not exists persons_auth_user_idx on public.persons(auth_user_id);

create table if not exists public.user_access_logs (
  id bigint generated by default as identity primary key,
  person_id uuid references public.persons(id) on delete set null,
  email text not null,
  event_type text not null check (event_type in ('login_success', 'login_failure', 'account_locked', 'logout', 'password_changed', 'password_reset')),
  user_agent text,
  occurred_at timestamptz not null default now(),
  session_id uuid,
  last_seen_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer not null default 0,
  ip_address inet
);

create table if not exists public.security_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.persons(id) on delete cascade,
  person_id uuid references public.persons(id) on delete set null,
  type text not null,
  title text not null,
  content text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

update public.persons set email = case lower(name)
  when 'dayana' then 'dayana@iracambi.com'
  when 'gabriela' then 'research@iracambi.com'
  when 'binka' then 'binka@iracambi.com'
  when 'arielle' then 'arielle@iracambi.com'
  when 'pierre' then 'volunteers@iracambi.com'
  when 'luiz' then 'luiz@iracambi.com'
  when 'thais' then 'thais@iracambi.com'
  when 'robin' then 'iracambi@iracambi.com'
  when 'luisa' then 'relacionamento@iracambi.com'
  when 'guilherme' then 'marketing@iracambi.com'
  when 'deivid' then 'viveiro@iracambi.com'
  when 'reinaldo' then 'reinaldo@iracambi.com'
  else email end;

update public.persons set access_role = 'admin' where lower(name) = 'reinaldo';
update public.persons set email = 'thais@iracambi.com' where lower(name) = 'thaís';
update public.persons set email = 'relacionamento@iracambi.com' where lower(name) = 'luísa';
update public.persons set managed_by = (select id from public.persons where lower(name) = 'reinaldo' limit 1)
where lower(name) in ('colegiado', 'colegiao');

-- As tabelas deixam de ser acessíveis com a chave pública sem uma sessão autenticada.
revoke all privileges on all tables in schema public from anon;
revoke all privileges on all sequences in schema public from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;

alter table public.user_access_logs enable row level security;
alter table public.security_notifications enable row level security;

drop policy if exists "admins_read_access_logs" on public.user_access_logs;
drop policy if exists "reinaldo_reads_access_logs" on public.user_access_logs;
create policy "reinaldo_reads_access_logs" on public.user_access_logs for select to authenticated using (
  exists (select 1 from public.persons where auth_user_id = auth.uid() and lower(email) = 'reinaldo@iracambi.com')
);
drop policy if exists "users_read_security_notifications" on public.security_notifications;
create policy "users_read_security_notifications" on public.security_notifications for select to authenticated using (
  recipient_id in (select id from public.persons where auth_user_id = auth.uid())
);
drop policy if exists "users_update_security_notifications" on public.security_notifications;
create policy "users_update_security_notifications" on public.security_notifications for update to authenticated using (
  recipient_id in (select id from public.persons where auth_user_id = auth.uid())
);
