/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1a3b2e",
        "primary-light": "#2e6b4f",
        accent: "#f5c542",
        surface: "#f9f9f9",
        background: "#ffffff",
        "on-primary": "#ffffff",
        "on-surface": "#1a1a1a",
        "surface-variant": "#e0e0e0",
        outline: "#9e9e9e",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        secondary: "#7c5730",
        tertiary: "#153800",
        "primary-container": "#2d4f1e",
        "on-primary-container": "#98c083",
        "secondary-container": "#fdcb9b",
        "tertiary-container": "#29500f",
        "on-secondary-container": "#79542d",
        "on-tertiary-container": "#94c274",
        "primary-fixed": "#c5efad",
        "secondary-fixed": "#ffdcbd",
        "tertiary-fixed": "#c0f19d",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-dim": "#dbdad5",
        "surface-bright": "#fbf9f4",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "inverse-primary": "#a9d293",
        "surface-tint": "#446733",
        // Modo escuro mais claro e translúcido
        "dark-background": "#3d3d3d",
        "dark-surface": "#4f4f4f",
        "dark-surface-variant": "#5f5f5f",
      },
      fontFamily: {
        epilogue: ["Epilogue", "sans-serif"],
        worksans: ["Work Sans", "sans-serif"],
        space: ["Space Grotesk", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        margin: "32px",
        sm: "12px",
        xs: "4px",
        md: "24px",
        base: "8px",
        lg: "48px",
        gutter: "24px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};