import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabaseClient";
import { deadlineState, money, PROJECT_STATUSES, PROJECT_TYPES, projectCode, projectProgress, statusInfo, typeInfo } from "../lib/projectManagement";
import { exportProjectsCsv } from "../lib/projectReportPdf";
import { useCurrentUser } from "../context/CurrentUserContext";

const inputClass = "rounded-xl border border-surface-variant bg-surface px-3 py-2.5 text-sm dark:border-white/10 dark:bg-gray-800 dark:text-white";

export default function Projects() {
  const { currentUser } = useCurrentUser();
  const [projects, setProjects] = useState([]);
  const [programs, setPrograms] = useState([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [view, setView] = useState("board");
  const [filters, setFilters] = useState({ search: "", program: "", type: "", priority: "", deadline: "" });
  const [draggedId, setDraggedId] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    const [projectResult, programResult] = await Promise.all([
      supabase.from("management_projects").select("*,program:program_id(id,name),manager:manager_id(id,name,initials,avatar_url),tasks:management_project_tasks(*,responsible:responsible_id(id,name)),risks:management_project_risks(*)").order("updated_at", { ascending: false }),
      supabase.from("programs").select("id,name").order("name"),
    ]);
    if (projectResult.error) setMessage(projectResult.error.message.includes("management_projects") ? "Execute project_management.sql no Supabase para ativar este módulo." : projectResult.error.message);
    setProjects(projectResult.data || []); setPrograms(programResult.data || []); setLoading(false);
  }, []);

  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);

  const filtered = useMemo(() => projects.filter((project) => {
    const haystack = `${project.title} ${project.description} ${project.category} ${project.manager?.name || ""}`.toLowerCase();
    return (!filters.search || haystack.includes(filters.search.toLowerCase()))
      && (!filters.program || project.program_id === filters.program)
      && (!filters.type || project.project_type === filters.type)
      && (!filters.priority || project.priority === filters.priority)
      && (!filters.deadline || deadlineState(project) === filters.deadline);
  }), [filters, projects]);

  async function moveProject(projectId, status) {
    const project = projects.find((item) => item.id === projectId);
    if (!project || project.status === status) return;
    const previous = project.status;
    setProjects((current) => current.map((item) => item.id === projectId ? { ...item, status, completed_at: status === "completed" ? new Date().toISOString() : item.completed_at } : item));
    const { error } = await supabase.from("management_projects").update({ status, completed_at: status === "completed" ? new Date().toISOString() : null }).eq("id", projectId);
    if (error) { setMessage(error.message); await load(); return; }
    await supabase.from("management_project_logs").insert({ project_id: projectId, actor_id: currentUser?.id, log_type: "status", content: `Situação alterada de “${statusInfo(previous).label}” para “${statusInfo(status).label}”.`, metadata: { from: previous, to: status } });
    const recipients = [...new Set([project.manager_id, ...(project.team_ids || [])])].filter((id) => id && id !== currentUser?.id);
    if (recipients.length) await supabase.from("management_project_notifications").insert(recipients.map((recipient_id) => ({ project_id: projectId, recipient_id, actor_id: currentUser?.id, title: "Projeto movimentado", content: `${project.title} agora está em ${statusInfo(status).label}.` })));
  }

  return <main className="mx-auto max-w-[1600px] px-2 sm:px-4">
    <header className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-primary-light dark:text-green-300">Portfólio institucional</p><h2 className="text-headline-lg font-semibold text-primary dark:text-white">Gestão de projetos</h2><p className="text-sm text-outline">Planeje, acompanhe e preste contas das iniciativas da organização.</p></div><div className="flex flex-wrap gap-2"><button disabled={!filtered.length} onClick={() => exportProjectsCsv(filtered)} className="inline-flex items-center gap-2 rounded-full border border-primary px-4 py-2.5 text-sm font-bold text-primary disabled:opacity-40 dark:text-white"><span className="material-symbols-outlined text-[19px]">download</span>Exportar CSV</button><Link to="/projects/new" className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 font-bold text-primary"><span className="material-symbols-outlined">add</span>Novo projeto</Link></div></header>
    {message && <div role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</div>}
    <section className="mb-4 grid gap-3 rounded-2xl border border-surface-variant bg-white p-4 dark:border-white/10 dark:bg-dark-surface md:grid-cols-2 xl:grid-cols-5"><input className={inputClass} value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Buscar projeto, categoria ou responsável" /><select className={inputClass} value={filters.program} onChange={(event) => setFilters({ ...filters, program: event.target.value })}><option value="">Todos os programas</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select><select className={inputClass} value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value })}><option value="">Todos os tipos</option>{PROJECT_TYPES.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select><select className={inputClass} value={filters.priority} onChange={(event) => setFilters({ ...filters, priority: event.target.value })}><option value="">Todas as prioridades</option><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select><select className={inputClass} value={filters.deadline} onChange={(event) => setFilters({ ...filters, deadline: event.target.value })}><option value="">Todos os prazos</option><option value="on_track">Dentro do prazo</option><option value="attention">Atenção</option><option value="overdue">Atrasados</option></select></section>
    <div className="mb-5 flex w-fit rounded-xl bg-surface p-1 dark:bg-gray-800">{[["board","view_kanban","Kanban"],["dashboard","monitoring","Painel"],["list","table_rows","Lista"]].map(([value, icon, label]) => <button key={value} onClick={() => setView(value)} className={`inline-flex items-center gap-1.5 rounded-lg px-4 py-2 text-sm font-bold ${view === value ? "bg-white text-primary shadow-sm dark:bg-gray-700 dark:text-white" : "text-outline"}`}><span className="material-symbols-outlined text-[18px]">{icon}</span>{label}</button>)}</div>
    {loading ? <p className="py-20 text-center text-outline">Carregando projetos…</p> : view === "board" ? <Kanban projects={filtered} draggedId={draggedId} setDraggedId={setDraggedId} onMove={moveProject} /> : view === "dashboard" ? <ProjectDashboard projects={filtered} /> : <ProjectList projects={filtered} />}
  </main>;
}

function Kanban({ projects, draggedId, setDraggedId, onMove }) {
  return <><p className="mb-3 rounded-xl bg-blue-50 p-3 text-xs text-blue-800 dark:bg-blue-950/30 dark:text-blue-300 md:hidden"><span className="material-symbols-outlined mr-1 align-middle text-[17px]">touch_app</span>No celular, use o seletor de etapa em cada cartão para movimentar o projeto.</p><section className="flex min-h-[520px] snap-x snap-mandatory gap-4 overflow-x-auto pb-5">{PROJECT_STATUSES.map((status) => {
    const items = projects.filter((project) => project.status === status.value);
    return <div key={status.value} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedId) onMove(draggedId, status.value); setDraggedId(null); }} className={`w-[calc(100vw-3.5rem)] max-w-[310px] shrink-0 snap-center rounded-2xl border p-3 transition ${draggedId ? "border-primary/40 bg-green-50/40 dark:bg-green-950/10" : "border-surface-variant bg-surface/70 dark:border-white/10 dark:bg-white/5"}`}><header className="mb-3 flex items-center gap-2"><span className="material-symbols-outlined rounded-lg bg-white p-1.5 text-primary shadow-sm dark:bg-gray-800 dark:text-green-300">{status.icon}</span><h3 className="flex-1 text-sm font-bold text-primary dark:text-white">{status.label}</h3><span className="rounded-full bg-white px-2 py-1 text-xs font-black text-outline dark:bg-gray-800">{items.length}</span></header><div className="space-y-3">{items.map((project) => <ProjectCard key={project.id} project={project} onMove={onMove} onDragStart={() => setDraggedId(project.id)} onDragEnd={() => setDraggedId(null)} />)}{!items.length && <div className="rounded-xl border border-dashed border-surface-variant p-6 text-center text-xs text-outline dark:border-white/10">Nenhum projeto nesta etapa</div>}</div></div>;
  })}</section></>;
}

function ProjectCard({ project, onDragStart, onDragEnd, onMove }) {
  const progress = projectProgress(project); const deadline = deadlineState(project); const type = typeInfo(project.project_type);
  const priorityClass = { critical: "bg-red-100 text-red-700", high: "bg-orange-100 text-orange-700", medium: "bg-blue-100 text-blue-700", low: "bg-gray-100 text-gray-600" }[project.priority];
  const typeClass = { strategic: "bg-violet-100 text-violet-700", operational: "bg-blue-100 text-blue-700", emergency: "bg-red-100 text-red-700", mandatory: "bg-amber-100 text-amber-700" }[project.project_type] || "bg-gray-100 text-gray-700";
  return <article draggable onDragStart={onDragStart} onDragEnd={onDragEnd} className="cursor-grab rounded-2xl border border-surface-variant bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing dark:border-white/10 dark:bg-dark-surface"><div className="flex items-start justify-between gap-2"><span className={`material-symbols-outlined rounded-lg p-1.5 ${typeClass}`}>{type.icon}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${priorityClass}`}>{project.priority === "critical" ? "Crítica" : project.priority === "high" ? "Alta" : project.priority === "medium" ? "Média" : "Baixa"}</span></div><Link to={`/projects/${project.id}`} className="mt-3 block"><p className="text-[10px] font-bold uppercase tracking-wider text-outline">{projectCode(project)} · {type.label}</p><h4 className="mt-1 font-bold leading-snug text-primary hover:underline dark:text-white">{project.title}</h4><p className="mt-1 truncate text-xs text-outline">{project.program?.name || project.category}</p></Link><div className="mt-4"><div className="mb-1 flex justify-between text-[11px] font-bold"><span>Progresso</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-surface dark:bg-gray-700"><div className="h-full rounded-full bg-gradient-to-r from-primary-light to-green-500" style={{ width: `${progress}%` }} /></div></div><div className="mt-3 flex items-center justify-between text-xs"><span className={`inline-flex items-center gap-1 font-bold ${deadline === "overdue" ? "text-red-600" : deadline === "attention" ? "text-amber-600" : "text-outline"}`}><span className="material-symbols-outlined text-[16px]">event</span>{project.planned_end ? project.planned_end.split("-").reverse().join("/") : "Sem prazo"}</span><span title={project.manager?.name} className="flex h-7 w-7 items-center justify-center overflow-hidden rounded-full bg-primary text-[10px] font-black text-white">{project.manager?.avatar_url ? <img src={project.manager.avatar_url} alt="" className="h-full w-full object-cover" /> : project.manager?.initials || "?"}</span></div>{project.risks?.some((risk) => risk.status !== "resolved" && risk.impact === "critical") && <div className="mt-3 flex items-center gap-1 rounded-lg bg-red-50 px-2 py-1.5 text-[11px] font-bold text-red-700"><span className="material-symbols-outlined text-[16px]">warning</span>Risco crítico aberto</div>}<label className="mt-3 block border-t border-surface-variant pt-3 text-[10px] font-bold uppercase text-outline md:hidden">Mover para<select value={project.status} onChange={(event) => onMove(project.id, event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-emerald-200 bg-emerald-50 px-3 text-sm font-bold normal-case text-primary dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-white">{PROJECT_STATUSES.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select></label></article>;
}

function ProjectDashboard({ projects }) {
  const totalBudget = projects.reduce((sum, item) => sum + Number(item.planned_budget || 0), 0); const actualBudget = projects.reduce((sum, item) => sum + Number(item.actual_budget || 0), 0);
  const cards = [["Projetos", projects.length, "folder_special", "bg-violet-100 text-violet-700"],["Em execução", projects.filter((p) => p.status === "in_progress").length, "rocket_launch", "bg-green-100 text-green-700"],["Atrasados", projects.filter((p) => deadlineState(p) === "overdue").length, "warning", "bg-red-100 text-red-700"],["Concluídos", projects.filter((p) => p.status === "completed").length, "task_alt", "bg-blue-100 text-blue-700"]];
  const maxStatus = Math.max(1, ...PROJECT_STATUSES.map((status) => projects.filter((project) => project.status === status.value).length));
  return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,icon,tone]) => <div key={label} className="rounded-2xl border border-surface-variant bg-white p-5 dark:border-white/10 dark:bg-dark-surface"><span className={`material-symbols-outlined rounded-xl p-2 ${tone}`}>{icon}</span><strong className="ml-3 text-3xl text-primary dark:text-white">{value}</strong><p className="mt-2 text-sm text-outline">{label}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><Chart title="Projetos por situação">{PROJECT_STATUSES.map((status) => { const count = projects.filter((project) => project.status === status.value).length; return <Bar key={status.value} label={status.label} value={count} width={(count / maxStatus) * 100} />; })}</Chart><Chart title="Projetos por tipo">{PROJECT_TYPES.map((type) => { const count = projects.filter((project) => project.project_type === type.value).length; return <Bar key={type.value} label={type.label} value={count} width={projects.length ? (count / projects.length) * 100 : 0} />; })}</Chart></div><div className="grid gap-5 lg:grid-cols-2"><Chart title="Execução financeira"><div className="grid grid-cols-2 gap-3"><Metric label="Previsto" value={money(totalBudget)} /><Metric label="Realizado" value={money(actualBudget)} /></div><div className="mt-4 h-4 overflow-hidden rounded-full bg-surface dark:bg-gray-700"><div className={`h-full ${actualBudget > totalBudget ? "bg-red-500" : "bg-green-500"}`} style={{ width: `${Math.min(100, totalBudget ? (actualBudget / totalBudget) * 100 : 0)}%` }} /></div><p className="mt-2 text-xs text-outline">{totalBudget ? Math.round((actualBudget / totalBudget) * 100) : 0}% do orçamento previsto executado</p></Chart><Chart title="Saúde dos prazos">{[["Dentro do prazo","on_track"],["Atenção","attention"],["Atrasados","overdue"]].map(([label,state]) => { const count = projects.filter((p) => deadlineState(p) === state).length; return <Bar key={state} label={label} value={count} width={projects.length ? count / projects.length * 100 : 0} />; })}</Chart></div></section>;
}

function ProjectList({ projects }) { return <><div className="grid gap-3 md:hidden">{projects.map((project) => <Link key={project.id} to={`/projects/${project.id}`} className="rounded-2xl border border-surface-variant bg-white p-4 shadow-sm dark:border-white/10 dark:bg-dark-surface"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-outline">{projectCode(project)} · {typeInfo(project.project_type).label}</p><h3 className="mt-1 font-bold text-primary dark:text-white">{project.title}</h3><p className="text-xs text-outline">{project.program?.name || project.category}</p></div><span className="rounded-full bg-surface px-2 py-1 text-[10px] font-bold dark:bg-gray-700">{statusInfo(project.status).label}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-outline">Responsável</dt><dd className="font-bold">{project.manager?.name || "—"}</dd></div><div><dt className="text-outline">Prazo</dt><dd className={deadlineState(project) === "overdue" ? "font-bold text-red-600" : "font-bold"}>{project.planned_end?.split("-").reverse().join("/") || "—"}</dd></div><div><dt className="text-outline">Progresso</dt><dd className="font-bold">{projectProgress(project)}%</dd></div><div><dt className="text-outline">Orçamento</dt><dd className="font-bold">{money(project.planned_budget)}</dd></div></dl></Link>)}</div><div className="hidden overflow-x-auto rounded-2xl border border-surface-variant bg-white dark:border-white/10 dark:bg-dark-surface md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-primary text-white"><tr>{["Código / Projeto","Tipo","Programa","Responsável","Prazo","Progresso","Orçamento","Situação"].map((head) => <th key={head} className="p-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-surface-variant dark:divide-white/10">{projects.map((project) => <tr key={project.id} className="hover:bg-surface dark:hover:bg-white/5"><td className="p-3"><Link to={`/projects/${project.id}`} className="font-bold text-primary hover:underline dark:text-green-300">{projectCode(project)} · {project.title}</Link><p className="text-xs text-outline">{project.category}</p></td><td className="p-3">{typeInfo(project.project_type).label}</td><td className="p-3">{project.program?.name || "—"}</td><td className="p-3">{project.manager?.name || "—"}</td><td className={`p-3 ${deadlineState(project) === "overdue" ? "font-bold text-red-600" : ""}`}>{project.planned_end?.split("-").reverse().join("/") || "—"}</td><td className="p-3 font-bold">{projectProgress(project)}%</td><td className="p-3">{money(project.planned_budget)}</td><td className="p-3"><span className="rounded-full bg-surface px-2 py-1 text-xs font-bold dark:bg-gray-700">{statusInfo(project.status).label}</span></td></tr>)}</tbody></table></div></>; }
function Chart({ title, children }) { return <div className="rounded-2xl border border-surface-variant bg-white p-5 dark:border-white/10 dark:bg-dark-surface"><h3 className="mb-4 font-bold text-primary dark:text-white">{title}</h3><div className="space-y-3">{children}</div></div>; }
function Bar({ label, value, width }) { return <div><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value}</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-surface dark:bg-gray-700"><div className="h-full rounded-full bg-gradient-to-r from-primary to-green-400 transition-all" style={{ width: `${width}%` }} /></div></div>; }
function Metric({ label, value }) { return <div className="rounded-xl bg-surface p-3 dark:bg-gray-800"><p className="text-xs text-outline">{label}</p><p className="mt-1 text-lg font-bold text-primary dark:text-white">{value}</p></div>; }
