import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { supabase } from "../lib/supabaseClient";
import { PROJECT_CATEGORIES, PROJECT_STATUSES, PROJECT_TYPES, PRIORITIES } from "../lib/projectManagement";
import { useCurrentUser } from "../context/CurrentUserContext";

const empty = { title: "", program_id: "", project_type: "operational", category: "Melhoria", status: "ideas", priority: "medium", description: "", need_statement: "", general_objective: "", specific_objectives_text: "", expected_results: "", location: "", planned_start: "", planned_end: "", actual_start: "", actual_end: "", manager_id: "", team_ids: [], beneficiaries: "", partners: "", funders: "", planned_budget: "", committed_budget: "", actual_budget: "", funding_source: "", progress_mode: "tasks", manual_progress: 0, notes: "" };
const inputClass = "w-full rounded-xl border border-surface-variant bg-surface px-3 py-2.5 text-on-surface focus:border-primary focus:ring-primary dark:border-white/10 dark:bg-gray-800 dark:text-white";

export default function ProjectEditor() {
  const { id } = useParams(); const navigate = useNavigate(); const { currentUser, persons } = useCurrentUser();
  const [form, setForm] = useState(empty); const [programs, setPrograms] = useState([]); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => {
    async function load() {
      const [programResult, projectResult] = await Promise.all([supabase.from("programs").select("id,name").order("name"), id ? supabase.from("management_projects").select("*").eq("id", id).single() : Promise.resolve({ data: null })]);
      setPrograms(programResult.data || []);
      if (projectResult.data) setForm({ ...empty, ...projectResult.data, program_id: projectResult.data.program_id || "", manager_id: projectResult.data.manager_id || "", team_ids: projectResult.data.team_ids || [], specific_objectives_text: (projectResult.data.specific_objectives || []).join("\n"), planned_budget: projectResult.data.planned_budget ?? "", committed_budget: projectResult.data.committed_budget ?? "", actual_budget: projectResult.data.actual_budget ?? "" });
      setLoading(false);
    }
    const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer);
  }, [id]);

  const field = (name) => ({ value: form[name] ?? "", onChange: (event) => setForm({ ...form, [name]: event.target.value }) });
  function toggleTeam(personId) { setForm((current) => ({ ...current, team_ids: current.team_ids.includes(personId) ? current.team_ids.filter((value) => value !== personId) : [...current.team_ids, personId] })); }
  async function save(event) {
    event.preventDefault(); setMessage("");
    if (!form.title.trim() || !form.description.trim() || !form.category || !form.project_type) return setMessage("Informe nome, descrição, categoria e tipo do projeto.");
    if (form.planned_start && form.planned_end && form.planned_end < form.planned_start) return setMessage("A conclusão prevista não pode ser anterior ao início.");
    const payload = { ...form, program_id: form.program_id || null, manager_id: form.manager_id || null, specific_objectives: form.specific_objectives_text.split("\n").map((item) => item.trim()).filter(Boolean), planned_budget: Number(form.planned_budget || 0), committed_budget: Number(form.committed_budget || 0), actual_budget: Number(form.actual_budget || 0), manual_progress: Number(form.manual_progress || 0), created_by: id ? form.created_by : currentUser?.id || null };
    delete payload.specific_objectives_text;
    setSaving(true);
    const result = id ? await supabase.from("management_projects").update(payload).eq("id", id).select().single() : await supabase.from("management_projects").insert(payload).select().single();
    setSaving(false);
    if (result.error) return setMessage(result.error.message);
    await supabase.from("management_project_logs").insert({ project_id: result.data.id, actor_id: currentUser?.id, log_type: id ? "updated" : "created", content: id ? "Dados gerais do projeto atualizados." : "Projeto cadastrado no portfólio." });
    const recipients = [...new Set([payload.manager_id, ...payload.team_ids])].filter((personId) => personId && personId !== currentUser?.id);
    if (recipients.length) await supabase.from("management_project_notifications").insert(recipients.map((recipient_id) => ({ project_id: result.data.id, recipient_id, actor_id: currentUser?.id, title: id ? "Projeto atualizado" : "Novo projeto", content: `${result.data.title} foi ${id ? "atualizado" : "adicionado ao portfólio"}.` })));
    navigate(`/projects/${result.data.id}`);
  }

  if (loading) return <p className="py-20 text-center text-outline">Carregando projeto…</p>;
  return <main className="mx-auto max-w-6xl px-2 sm:px-4"><button onClick={() => navigate(id ? `/projects/${id}` : "/projects")} className="mb-3 inline-flex items-center gap-1 text-sm font-bold text-primary dark:text-green-300"><span className="material-symbols-outlined text-[18px]">arrow_back</span>Voltar</button><header className="mb-5"><p className="text-sm font-semibold text-primary-light">Portfólio institucional</p><h2 className="text-headline-lg font-semibold text-primary dark:text-white">{id ? "Editar projeto" : "Cadastrar projeto"}</h2><p className="text-sm text-outline">Estruture a necessidade, os objetivos, os responsáveis, o prazo e os recursos.</p></header>{message && <div role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</div>}<form onSubmit={save} className="space-y-5">
    <Section icon="identity_platform" title="Identificação e classificação"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Nome do projeto *" wide><input required className={inputClass} {...field("title")} /></Field><Field label="Programa relacionado"><select className={inputClass} {...field("program_id")}><option value="">Sem programa</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></Field><Field label="Categoria *"><select className={inputClass} {...field("category")}>{PROJECT_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Tipo *"><select className={inputClass} {...field("project_type")}>{PROJECT_TYPES.map((type) => <option key={type.value} value={type.value}>{type.label} — {type.description}</option>)}</select></Field><Field label="Situação"><select className={inputClass} {...field("status")}>{PROJECT_STATUSES.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select></Field><Field label="Prioridade"><select className={inputClass} {...field("priority")}>{PRIORITIES.map((priority) => <option key={priority.value} value={priority.value}>{priority.label}</option>)}</select></Field><Field label="Local de execução" wide><input className={inputClass} {...field("location")} /></Field></div></Section>
    <Section icon="target" title="Necessidade, objetivos e resultados"><div className="grid gap-4 md:grid-cols-2"><Field label="Descrição do projeto *" wide><textarea required rows="4" className={inputClass} {...field("description")} /></Field><Field label="Problema ou necessidade identificada"><textarea rows="4" className={inputClass} {...field("need_statement")} /></Field><Field label="Objetivo geral"><textarea rows="4" className={inputClass} {...field("general_objective")} /></Field><Field label="Objetivos específicos (um por linha)"><textarea rows="4" className={inputClass} {...field("specific_objectives_text")} /></Field><Field label="Resultados esperados"><textarea rows="4" className={inputClass} {...field("expected_results")} /></Field></div></Section>
    <Section icon="calendar_month" title="Cronograma"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Início previsto"><input type="date" className={inputClass} {...field("planned_start")} /></Field><Field label="Conclusão prevista"><input type="date" className={inputClass} {...field("planned_end")} /></Field><Field label="Início real"><input type="date" className={inputClass} {...field("actual_start")} /></Field><Field label="Conclusão real"><input type="date" className={inputClass} {...field("actual_end")} /></Field></div></Section>
    <Section icon="groups" title="Responsáveis e partes interessadas"><div className="grid gap-4 md:grid-cols-2"><Field label="Gestor responsável"><select className={inputClass} {...field("manager_id")}><option value="">Selecione</option>{persons.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><Field label="Beneficiários / público impactado"><input className={inputClass} {...field("beneficiaries")} /></Field><Field label="Parceiros"><textarea rows="3" className={inputClass} {...field("partners")} /></Field><Field label="Financiadores"><textarea rows="3" className={inputClass} {...field("funders")} /></Field><div className="md:col-span-2"><p className="mb-2 text-sm font-medium text-primary dark:text-gray-200">Equipe envolvida</p><div className="flex max-h-44 flex-wrap gap-2 overflow-y-auto rounded-xl border border-surface-variant p-3 dark:border-white/10">{persons.map((person) => <label key={person.id} className={`cursor-pointer rounded-full border px-3 py-2 text-sm ${form.team_ids.includes(person.id) ? "border-primary bg-green-50 font-bold text-primary" : "border-surface-variant"}`}><input type="checkbox" checked={form.team_ids.includes(person.id)} onChange={() => toggleTeam(person.id)} className="mr-2 rounded text-primary" />{person.name}</label>)}</div></div></div></Section>
    <Section icon="payments" title="Planejamento financeiro"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Orçamento previsto"><input type="number" min="0" step="0.01" className={inputClass} {...field("planned_budget")} /></Field><Field label="Valor comprometido"><input type="number" min="0" step="0.01" className={inputClass} {...field("committed_budget")} /></Field><Field label="Valor realizado"><input type="number" min="0" step="0.01" className={inputClass} {...field("actual_budget")} /></Field><Field label="Fonte dos recursos"><input className={inputClass} {...field("funding_source")} /></Field></div></Section>
    <Section icon="monitoring" title="Medição do progresso"><div className="grid gap-4 md:grid-cols-2"><Field label="Forma de cálculo"><select className={inputClass} {...field("progress_mode")}><option value="tasks">Tarefas concluídas</option><option value="weighted">Etapas/tarefas ponderadas</option><option value="manual">Percentual informado manualmente</option></select></Field>{form.progress_mode === "manual" && <Field label="Progresso atual (%)"><input type="number" min="0" max="100" className={inputClass} {...field("manual_progress")} /></Field>}<Field label="Observações gerais" wide><textarea rows="4" className={inputClass} {...field("notes")} /></Field></div></Section>
    <div className="sticky bottom-16 z-20 flex flex-wrap justify-end gap-3 rounded-2xl border border-surface-variant bg-white/95 p-3 shadow-xl backdrop-blur dark:border-white/10 dark:bg-dark-surface/95 sm:p-4 md:bottom-4"><button type="button" onClick={() => navigate(id ? `/projects/${id}` : "/projects")} className="min-h-11 flex-1 rounded-full border border-outline px-5 py-2.5 sm:flex-none">Cancelar</button><button disabled={saving} className="min-h-11 flex-1 rounded-full bg-primary px-6 py-2.5 font-bold text-white disabled:opacity-50 sm:flex-none">{saving ? "Salvando…" : id ? "Salvar alterações" : "Cadastrar projeto"}</button></div>
  </form></main>;
}

function Section({ icon, title, children }) { const [expanded, setExpanded] = useState(true); return <details open={expanded} onToggle={(event) => setExpanded(event.currentTarget.open)} className="group rounded-2xl border border-surface-variant bg-white p-4 dark:border-white/10 dark:bg-dark-surface sm:p-6"><summary className="flex min-h-12 cursor-pointer list-none items-center gap-3"><span className="material-symbols-outlined rounded-xl bg-green-100 p-2 text-primary dark:bg-green-900/30 dark:text-green-300">{icon}</span><h3 className="flex-1 text-base font-bold text-primary dark:text-white sm:text-lg">{title}</h3><span className="material-symbols-outlined text-outline transition group-open:rotate-180">expand_more</span></summary><div className="mt-5 border-t border-surface-variant pt-5 dark:border-white/10">{children}</div></details>; }
function Field({ label, wide, children }) { return <label className={wide ? "md:col-span-2" : ""}><span className="mb-1.5 block text-sm font-medium text-primary dark:text-gray-200">{label}</span>{children}</label>; }
