/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useCurrentUser } from "../context/CurrentUserContext";

const blank = { school_name:"",visit_date:"",expected_arrival:"",expected_departure:"",total_people:"",adults:"",children:"",breakfast_people:"",lunch_people:"",afternoon_coffee_people:"",dietary_restrictions:"",notes:"",estimated_meal_total:"",responsible_id:"",activity_id:"",future_activity_title:"" };
const cls = "w-full rounded-xl border border-surface-variant bg-surface px-3 py-2.5 dark:bg-gray-800";
export default function SchoolVisits(){
 const {currentUser,persons}=useCurrentUser(); const [items,setItems]=useState([]); const [activities,setActivities]=useState([]); const [program,setProgram]=useState(null); const [form,setForm]=useState(blank); const [open,setOpen]=useState(false); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 async function load(){const [v,a,p]=await Promise.all([supabase.from("school_visits").select("*,responsible:responsible_id(name),activity:activity_id(title)").order("visit_date",{ascending:false}),supabase.from("activities").select("id,title,due_date").order("due_date").limit(200),supabase.from("programs").select("id,name").ilike("name","%Educa%Ambiental%").limit(1).maybeSingle()]);setItems(v.data||[]);setActivities(a.data||[]);setProgram(p.data||null);if(v.error)setMessage(v.error.message)}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setSaving(true);setMessage("");if(Number(form.adults||0)+Number(form.children||0)>Number(form.total_people)){setSaving(false);return setMessage("Adultos e crianças não podem superar o total de visitantes.")}let activity_id=form.activity_id||null;if(!activity_id&&form.future_activity_title.trim()){const r=await supabase.from("activities").insert({title:form.future_activity_title.trim(),description:`Visita da escola ${form.school_name}`,due_date:form.visit_date,week_start:form.visit_date,status:"Planejado",priority:"Média",program_id:program?.id||null,responsible_id:form.responsible_id,created_by:currentUser.id}).select("id").single();if(r.error){setSaving(false);return setMessage(r.error.message)}activity_id=r.data.id}const payload={...form,activity_id,program_id:program?.id||null,created_by:currentUser.id};["total_people","adults","children","breakfast_people","lunch_people","afternoon_coffee_people","estimated_meal_total"].forEach(k=>payload[k]=Number(form[k]||0));["expected_arrival","expected_departure","activity_id","future_activity_title"].forEach(k=>{if(!payload[k])payload[k]=null});const r=await supabase.from("school_visits").insert(payload);setSaving(false);if(r.error)return setMessage(r.error.message);setOpen(false);setMessage("Visita registrada com sucesso.");load()}
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 return <main className="mx-auto max-w-6xl space-y-5 px-2 sm:px-4"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary-light">Educação ambiental</p><h1 className="text-3xl font-black text-primary dark:text-white">Visitas escolares</h1><p className="text-outline">Planejamento do público, alimentação e atividade relacionada.</p></div><button onClick={()=>{setForm({...blank,visit_date:new Date().toISOString().slice(0,10),responsible_id:currentUser.id});setOpen(true)}} className="rounded-full bg-accent px-5 py-3 font-black">+ Agendar visita</button></header>{message&&<p className="rounded-xl bg-amber-50 p-3 text-amber-800">{message}</p>}<section className="grid gap-4 md:grid-cols-2">{items.length?items.map(v=><article key={v.id} className="rounded-2xl border bg-white p-5 dark:bg-dark-surface"><p className="text-xs font-black text-primary-light">{new Date(`${v.visit_date}T12:00`).toLocaleDateString("pt-BR")}</p><h2 className="text-xl font-bold text-primary dark:text-white">{v.school_name}</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Info n="Pessoas" v={v.total_people}/><Info n="Adultos / crianças" v={`${v.adults} / ${v.children}`}/><Info n="Almoços" v={v.lunch_people}/><Info n="Cafés manhã / tarde" v={`${v.breakfast_people} / ${v.afternoon_coffee_people}`}/><Info n="Chegada / partida" v={`${v.expected_arrival?.slice(0,5)||"—"} / ${v.expected_departure?.slice(0,5)||"—"}`}/><Info n="Previsão" v={Number(v.estimated_meal_total).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}/></div><p className="mt-3 text-sm"><b>Responsável:</b> {v.responsible?.name}</p>{v.activity&&<p className="text-sm"><b>Atividade:</b> {v.activity.title}</p>}{v.dietary_restrictions&&<p className="mt-2 rounded-lg bg-amber-50 p-2 text-sm"><b>Restrições:</b> {v.dietary_restrictions}</p>}</article>):<p className="col-span-2 rounded-2xl border border-dashed p-10 text-center text-outline">Nenhuma visita cadastrada.</p>}</section>
 {open&&<div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/50 p-3"><form onSubmit={save} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 dark:bg-dark-surface"><div className="mb-4 flex justify-between"><h2 className="text-2xl font-black">Agendar visita escolar</h2><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="grid gap-4 sm:grid-cols-2"><F l="Escola *"><input required className={cls} value={form.school_name} onChange={e=>set("school_name",e.target.value)}/></F><F l="Data *"><input required type="date" className={cls} value={form.visit_date} onChange={e=>set("visit_date",e.target.value)}/></F><F l="Chegada"><input type="time" className={cls} value={form.expected_arrival} onChange={e=>set("expected_arrival",e.target.value)}/></F><F l="Partida"><input type="time" className={cls} value={form.expected_departure} onChange={e=>set("expected_departure",e.target.value)}/></F>{[["total_people","Total de pessoas *"],["adults","Adultos"],["children","Crianças"],["breakfast_people","Café da manhã"],["lunch_people","Almoço"],["afternoon_coffee_people","Café da tarde"]].map(([k,l])=><F key={k} l={l}><input required={k==="total_people"} min="0" type="number" className={cls} value={form[k]} onChange={e=>set(k,e.target.value)}/></F>)}<F l="Responsável *"><select required className={cls} value={form.responsible_id} onChange={e=>set("responsible_id",e.target.value)}><option value="">Selecione</option>{persons.filter(p=>p.is_active!==false).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></F><F l="Total previsto das refeições"><input min="0" step=".01" type="number" className={cls} value={form.estimated_meal_total} onChange={e=>set("estimated_meal_total",e.target.value)}/></F><div className="sm:col-span-2"><F l="Atividade existente"><select className={cls} value={form.activity_id} onChange={e=>set("activity_id",e.target.value)}><option value="">Nenhuma</option>{activities.map(a=><option key={a.id} value={a.id}>{a.due_date} · {a.title}</option>)}</select></F></div><div className="sm:col-span-2"><F l="Ou criar atividade"><input disabled={!!form.activity_id} className={cls} value={form.future_activity_title} onChange={e=>set("future_activity_title",e.target.value)}/></F></div><div className="sm:col-span-2"><F l="Restrições alimentares"><textarea className={cls} value={form.dietary_restrictions} onChange={e=>set("dietary_restrictions",e.target.value)}/></F></div><div className="sm:col-span-2"><F l="Observações"><textarea className={cls} value={form.notes} onChange={e=>set("notes",e.target.value)}/></F></div></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="px-5">Cancelar</button><button disabled={saving} className="rounded-full bg-primary px-6 py-3 font-bold text-white">{saving?"Salvando…":"Salvar visita"}</button></div></form></div>}</main>}
function F({l,children}){return <label className="block text-sm font-bold"><span className="mb-1 block">{l}</span>{children}</label>};function Info({n,v}){return <div className="rounded-lg bg-surface p-2"><span className="block text-xs text-outline">{n}</span><b>{v}</b></div>}
