-- Solicitações de compras. Migração versionada; aplicada com Supabase CLI após project_management.sql
-- e expense_report_approvals.sql.

create table if not exists public.purchase_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  requester_id uuid not null references public.persons(id) on delete restrict,
  title text not null,
  request_type text not null default 'goods' check (request_type in ('goods','services','works')),
  urgency text not null default 'normal' check (urgency in ('low','normal','high','critical')),
  status text not null default 'draft' check (status in ('draft','pending_approval','changes_requested','rejected','approved','quotation','ordered','partially_received','received','cancelled')),
  justification text not null,
  needed_by date,
  management_project_id uuid references public.management_projects(id) on delete set null,
  edital_name text, edital_number text, edital_deadline date, funding_source text,
  program_ids uuid[] not null default '{}',
  beneficiary_person_ids uuid[] not null default '{}',
  beneficiary_description text, supplier_suggestion text, delivery_location text,
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  estimated_total numeric(14,2) not null default 0 check (estimated_total >= 0),
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  submitted_at timestamptz, approved_at timestamptz, ordered_at timestamptz, received_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (edital_deadline is null or edital_name is not null),
  check (status = 'draft' or jsonb_array_length(items) > 0)
);

create table if not exists public.purchase_request_approvals (
  id uuid primary key default gen_random_uuid(), request_id uuid not null references public.purchase_requests(id) on delete cascade,
  approver_id uuid not null references public.persons(id) on delete restrict,
  decision text not null default 'pending' check (decision in ('pending','approved','changes_requested','rejected')),
  comment text, decided_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(request_id, approver_id)
);
create table if not exists public.purchase_request_history (
  id bigint generated always as identity primary key, request_id uuid not null references public.purchase_requests(id) on delete cascade,
  actor_id uuid references public.persons(id) on delete set null, event_type text not null, content text not null,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.purchase_request_notifications (
  id uuid primary key default gen_random_uuid(), request_id uuid not null references public.purchase_requests(id) on delete cascade,
  recipient_id uuid not null references public.persons(id) on delete cascade, actor_id uuid references public.persons(id) on delete set null,
  type text not null, title text not null, content text not null, read_at timestamptz, created_at timestamptz not null default now()
);

create index if not exists purchase_requests_status_idx on public.purchase_requests(status,created_at desc);
create index if not exists purchase_requests_requester_idx on public.purchase_requests(requester_id,created_at desc);
create index if not exists purchase_requests_project_idx on public.purchase_requests(management_project_id);
create index if not exists purchase_requests_programs_idx on public.purchase_requests using gin(program_ids);
create index if not exists purchase_approvals_approver_idx on public.purchase_request_approvals(approver_id,decision);
create index if not exists purchase_history_request_idx on public.purchase_request_history(request_id,created_at desc);
create index if not exists purchase_notifications_recipient_idx on public.purchase_request_notifications(recipient_id,read_at,created_at desc);

drop trigger if exists purchase_requests_updated_at on public.purchase_requests;
create trigger purchase_requests_updated_at before update on public.purchase_requests for each row execute function public.set_updated_at();
drop trigger if exists purchase_approvals_updated_at on public.purchase_request_approvals;
create trigger purchase_approvals_updated_at before update on public.purchase_request_approvals for each row execute function public.set_updated_at();

alter table public.purchase_requests enable row level security;
alter table public.purchase_request_approvals enable row level security;
alter table public.purchase_request_history enable row level security;
alter table public.purchase_request_notifications enable row level security;
drop policy if exists purchase_requests_active_read on public.purchase_requests;
drop policy if exists purchase_requests_author_insert on public.purchase_requests;
drop policy if exists purchase_requests_author_update on public.purchase_requests;
drop policy if exists purchase_requests_admin_delete on public.purchase_requests;
drop policy if exists purchase_approvals_active_read on public.purchase_request_approvals;
drop policy if exists purchase_history_active_read on public.purchase_request_history;
drop policy if exists purchase_notifications_own_read on public.purchase_request_notifications;
drop policy if exists purchase_notifications_own_update on public.purchase_request_notifications;
create policy purchase_requests_active_read on public.purchase_requests for select to authenticated using (public.is_active_user());
create policy purchase_requests_author_insert on public.purchase_requests for insert to authenticated with check (public.is_active_user() and requester_id=public.current_person_id() and status='draft');
create policy purchase_requests_author_update on public.purchase_requests for update to authenticated
  using (public.is_admin() or (requester_id=public.current_person_id() and status in ('draft','changes_requested'))) with check (public.is_active_user());
create policy purchase_requests_admin_delete on public.purchase_requests for delete to authenticated using (public.is_admin());
create policy purchase_approvals_active_read on public.purchase_request_approvals for select to authenticated using (public.is_active_user());
create policy purchase_history_active_read on public.purchase_request_history for select to authenticated using (public.is_active_user());
create policy purchase_notifications_own_read on public.purchase_request_notifications for select to authenticated using (recipient_id=public.current_person_id() or public.is_admin());
create policy purchase_notifications_own_update on public.purchase_request_notifications for update to authenticated using (recipient_id=public.current_person_id()) with check (recipient_id=public.current_person_id());
grant select,insert,update,delete on public.purchase_requests to authenticated;
grant select on public.purchase_request_approvals,public.purchase_request_history to authenticated;
grant select,update on public.purchase_request_notifications to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.initialize_purchase_request_approval(target_request_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare r public.purchase_requests%rowtype; actor uuid:=public.current_person_id(); rid uuid; tid uuid; required uuid[]; recipient uuid;
begin
  select * into r from public.purchase_requests where id=target_request_id for update;
  if r.id is null then raise exception 'Solicitação não encontrada.'; end if;
  if actor is null or actor is distinct from r.requester_id then raise exception 'Somente o solicitante pode enviar esta solicitação.'; end if;
  if r.status not in ('draft','changes_requested') then raise exception 'Esta solicitação não pode ser enviada neste estado.'; end if;
  if nullif(trim(r.title),'') is null or nullif(trim(r.justification),'') is null or jsonb_array_length(r.items)=0 then raise exception 'Informe título, justificativa e ao menos um item.'; end if;
  select person_id into rid from public.expense_approval_config where approver_key='reinaldo' and is_active;
  select person_id into tid from public.expense_approval_config where approver_key='thais' and is_active;
  if rid is null or tid is null then raise exception 'Configure Reinaldo e Thaís como aprovadores.'; end if;
  required:=case when actor=rid then array[tid] when actor=tid then array[rid] else array[rid,tid] end;
  delete from public.purchase_request_approvals where request_id=target_request_id;
  insert into public.purchase_request_approvals(request_id,approver_id) select target_request_id,unnest(required);
  update public.purchase_requests set status='pending_approval',submitted_at=now(),approved_at=null where id=target_request_id;
  insert into public.purchase_request_history(request_id,actor_id,event_type,content) values(target_request_id,actor,'submitted','Solicitação enviada para aprovação.');
  foreach recipient in array required loop
    insert into public.purchase_request_notifications(request_id,recipient_id,actor_id,type,title,content)
    values(target_request_id,recipient,actor,'approval_requested','Nova solicitação de compra','A solicitação nº '||lpad(r.request_number::text,5,'0')||' aguarda sua análise.');
  end loop;
end $$;

-- Linha do tempo operacional imutável: cada passo da equipe permanece individualizado.
create table if not exists public.purchase_request_steps (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.purchase_requests(id) on delete cascade,
  actor_id uuid not null references public.persons(id) on delete restrict,
  step_type text not null check (step_type in (
    'comment','quotation_requested','quotation_received','supplier_selected','order_issued',
    'invoice_received','payment_scheduled','payment_completed','partial_receipt','receipt_completed','document_added'
  )),
  title text not null,
  description text,
  supplier_name text,
  document_number text,
  amount numeric(14,2) check (amount is null or amount >= 0),
  event_date date not null default current_date,
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments)='array'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists purchase_steps_request_idx on public.purchase_request_steps(request_id,created_at desc);
alter table public.purchase_request_steps enable row level security;
drop policy if exists purchase_steps_active_read on public.purchase_request_steps;
create policy purchase_steps_active_read on public.purchase_request_steps for select to authenticated using (public.is_active_user());
grant select on public.purchase_request_steps to authenticated;

create or replace function public.record_purchase_request_step(
  target_request_id uuid, requested_step_type text, step_title text, step_description text default null,
  step_supplier_name text default null, step_document_number text default null, step_amount numeric default null,
  step_event_date date default current_date, step_attachments jsonb default '[]'::jsonb
) returns uuid language plpgsql security definer set search_path=public as $$
declare actor uuid:=public.current_person_id(); r public.purchase_requests%rowtype; new_id uuid; resulting_status text;
begin
  if actor is null or not public.is_active_user() then raise exception 'Usuário sem acesso ativo.'; end if;
  if requested_step_type not in ('comment','quotation_requested','quotation_received','supplier_selected','order_issued','invoice_received','payment_scheduled','payment_completed','partial_receipt','receipt_completed','document_added') then raise exception 'Tipo de etapa inválido.'; end if;
  if nullif(trim(step_title),'') is null then raise exception 'Informe o título do registro.'; end if;
  select * into r from public.purchase_requests where id=target_request_id for update;
  if r.id is null then raise exception 'Solicitação não encontrada.'; end if;
  if requested_step_type not in ('comment','document_added') and not public.is_admin() and not exists(select 1 from public.expense_approval_config where person_id=actor and is_active) then raise exception 'Etapa restrita aos responsáveis pelo processo de compras.'; end if;
  if requested_step_type in ('quotation_received','supplier_selected') and nullif(trim(step_supplier_name),'') is null then raise exception 'Informe o fornecedor.'; end if;
  if requested_step_type in ('order_issued','invoice_received') and nullif(trim(step_document_number),'') is null then raise exception 'Informe o número do documento.'; end if;
  if jsonb_typeof(coalesce(step_attachments,'[]'::jsonb))<>'array' then raise exception 'Anexos inválidos.'; end if;

  insert into public.purchase_request_steps(request_id,actor_id,step_type,title,description,supplier_name,document_number,amount,event_date,attachments)
  values(target_request_id,actor,requested_step_type,trim(step_title),nullif(trim(step_description),''),nullif(trim(step_supplier_name),''),nullif(trim(step_document_number),''),step_amount,coalesce(step_event_date,current_date),coalesce(step_attachments,'[]'::jsonb)) returning id into new_id;

  resulting_status:=case requested_step_type
    when 'quotation_received' then 'quotation' when 'supplier_selected' then 'quotation'
    when 'order_issued' then 'ordered' when 'partial_receipt' then 'partially_received'
    when 'receipt_completed' then 'received' else null end;
  if resulting_status is not null then
    update public.purchase_requests set status=resulting_status,
      ordered_at=case when resulting_status='ordered' then now() else ordered_at end,
      received_at=case when resulting_status='received' then now() else received_at end
    where id=target_request_id;
  end if;
  insert into public.purchase_request_history(request_id,actor_id,event_type,content,metadata)
  values(target_request_id,actor,'operational_step',trim(step_title),jsonb_build_object('step_id',new_id,'step_type',requested_step_type,'status',resulting_status));
  if r.requester_id<>actor then
    insert into public.purchase_request_notifications(request_id,recipient_id,actor_id,type,title,content)
    values(target_request_id,r.requester_id,actor,'operational_step','Movimentação na solicitação de compra','Novo registro em '||lpad(r.request_number::text,5,'0')||': '||trim(step_title));
  end if;
  return new_id;
end $$;
revoke all on function public.record_purchase_request_step(uuid,text,text,text,text,text,numeric,date,jsonb) from public;
grant execute on function public.record_purchase_request_step(uuid,text,text,text,text,text,numeric,date,jsonb) to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='purchase_request_steps') then alter publication supabase_realtime add table public.purchase_request_steps; end if;
end $$;

create or replace function public.decide_purchase_request(target_request_id uuid,requested_decision text,decision_comment text default null)
returns text language plpgsql security definer set search_path=public as $$
declare actor uuid:=public.current_person_id(); actor_name text; r public.purchase_requests%rowtype; pending integer; resulting text;
begin
  if requested_decision not in ('approved','changes_requested','rejected') then raise exception 'Decisão inválida.'; end if;
  if requested_decision<>'approved' and nullif(trim(decision_comment),'') is null then raise exception 'Informe a justificativa da decisão.'; end if;
  select * into r from public.purchase_requests where id=target_request_id for update;
  select name into actor_name from public.persons where id=actor;
  if r.id is null then raise exception 'Solicitação não encontrada.'; end if;
  if actor=r.requester_id then raise exception 'O solicitante não pode aprovar a própria solicitação.'; end if;
  update public.purchase_request_approvals set decision=requested_decision,comment=nullif(trim(decision_comment),''),decided_at=now()
    where request_id=target_request_id and approver_id=actor and decision='pending';
  if not found then raise exception 'Você não possui aprovação pendente para esta solicitação.'; end if;
  if requested_decision in ('rejected','changes_requested') then resulting:=requested_decision;
  else select count(*) into pending from public.purchase_request_approvals where request_id=target_request_id and decision='pending'; resulting:=case when pending=0 then 'approved' else 'pending_approval' end; end if;
  update public.purchase_requests set status=resulting,approved_at=case when resulting='approved' then now() else null end where id=target_request_id;
  insert into public.purchase_request_history(request_id,actor_id,event_type,content,metadata)
    values(target_request_id,actor,requested_decision,coalesce(nullif(trim(decision_comment),''),actor_name||' aprovou a solicitação.'),jsonb_build_object('status',resulting));
  insert into public.purchase_request_notifications(request_id,recipient_id,actor_id,type,title,content)
    values(target_request_id,r.requester_id,actor,resulting,case resulting when 'approved' then 'Solicitação aprovada' when 'pending_approval' then 'Aprovação parcial' when 'changes_requested' then 'Ajustes solicitados' else 'Solicitação reprovada' end,'A solicitação nº '||lpad(r.request_number::text,5,'0')||' foi analisada por '||actor_name||'.');
  return resulting;
end $$;

create or replace function public.advance_purchase_request(target_request_id uuid,next_status text,transition_comment text default null)
returns void language plpgsql security definer set search_path=public as $$
declare actor uuid:=public.current_person_id(); current_status text; requester uuid; request_no bigint;
begin
  if not public.is_admin() and not exists(select 1 from public.expense_approval_config where person_id=actor and is_active) then raise exception 'Operação restrita aos responsáveis por compras.'; end if;
  select status,requester_id,request_number into current_status,requester,request_no from public.purchase_requests where id=target_request_id for update;
  if not ((current_status='approved' and next_status in ('quotation','ordered','cancelled')) or (current_status='quotation' and next_status in ('ordered','cancelled')) or (current_status='ordered' and next_status in ('partially_received','received','cancelled')) or (current_status='partially_received' and next_status in ('received','cancelled'))) then raise exception 'Transição de situação inválida.'; end if;
  update public.purchase_requests set status=next_status,ordered_at=case when next_status='ordered' then now() else ordered_at end,received_at=case when next_status='received' then now() else received_at end where id=target_request_id;
  insert into public.purchase_request_history(request_id,actor_id,event_type,content,metadata) values(target_request_id,actor,'status',coalesce(nullif(trim(transition_comment),''),'Situação alterada para '||next_status||'.'),jsonb_build_object('from',current_status,'to',next_status));
  insert into public.purchase_request_notifications(request_id,recipient_id,actor_id,type,title,content) values(target_request_id,requester,actor,next_status,'Atualização da solicitação de compra','A solicitação nº '||lpad(request_no::text,5,'0')||' avançou para: '||next_status||'.');
end $$;

revoke all on function public.initialize_purchase_request_approval(uuid) from public;
revoke all on function public.decide_purchase_request(uuid,text,text) from public;
revoke all on function public.advance_purchase_request(uuid,text,text) from public;
grant execute on function public.initialize_purchase_request_approval(uuid) to authenticated;
grant execute on function public.decide_purchase_request(uuid,text,text) to authenticated;
grant execute on function public.advance_purchase_request(uuid,text,text) to authenticated;
do $$ begin
  if to_regprocedure('public.capture_system_audit()') is not null then
    drop trigger if exists system_audit_trigger on public.purchase_requests;
    create trigger system_audit_trigger after insert or update or delete on public.purchase_requests for each row execute function public.capture_system_audit();
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='purchase_request_notifications') then alter publication supabase_realtime add table public.purchase_request_notifications; end if;
end $$;
